### ISSUE TITLE
How do you collect these data

### ISSUE THREAD

**Issue by Tie-1** [JewelryForge/motor_data#1]
Hi @JewelryForge , thanks for your public work.
I have a question that how did you collect the following data and what do these data mean?
![image](https://user-images.githubusercontent.com/77917350/181029128-27efcec7-2e09-4491-9626-9c5de153deb6.png)

**Comment by JewelryForge** [comment]
Sorry, the data is collected just for self use.
The data is collected as [_Learning agile and dynamic motor skills for legged robots_]( https://www.science.org/doi/abs/10.1126/scirobotics.aau5872) described, and is used for neural network identification of the motor of Aliengo, which is a quadruped robot.

**Comment by Tie-1** [comment]
Thank you!

**Comment by Tie-1** [comment]
Thank you for your answer! Did you collect these data yourself or provided by YuShu?

**Comment by JewelryForge** [comment]
> Thank you for your answer! Did you collect these data yourself or provided by YuShu?

I collected it myself under a fixed trajectory generator, with kp=150, kd=4.

**Comment by Tie-1** [comment]
> > Thank you for your answer! Did you collect these data yourself or provided by YuShu?
> 
> I collected it myself under a fixed trajectory generator, with kp=150, kd=4.

Thank you for your guidance.
